import { useSelector } from "react-redux";
import Head from "next/head";

//Images

//Components
import Header from "../../components/Custom/Header/Header";
import HeaderCart from "../../components/Cart/Header/HeaderCart";

//Containers
import CartContainer from "../../components/Containers/CartContainer/CartContainer";
import CartTable from "../../components/Cart/Table/CartTable";
import ShopSummary from "../../components/Cart/ShopSummary/ShopSummary";

export default function Home() {
  const { total } = useSelector(store => store.products);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />

        <CartContainer>
          <div className="w-full md:w-3/5 ">
            <HeaderCart />
            <CartTable />
          </div>
          <div className="w-full md:w-1/3">{total > 0 && <ShopSummary />}</div>
        </CartContainer>
      </main>
    </div>
  );
}
