import Head from "next/head";

//Components
import ContactForm from "../../components/Contacto/ContactForm";

function Contacto() {
  return (
    <div>
      <Head>
        <title>Contacto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ContactForm />
      </main>
    </div>
  );
}

export default Contacto;
