import React, { useState, useEffect } from "react";

import Head from "next/head";

const Users = () => {
  const [users, setUsers] = useState([]);

  useEffect(() => {
    const handleUsers = async () => {
      const response = await fetch(
        "https://jsonplaceholder.typicode.com/users"
      );
      const result = await response.json();
      setUsers(result);
    };

    handleUsers();
  }, []);

  const handleAddUser = async () => {
    const response = await fetch("http://localhost:3000/api/users", {
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json"
      },
      method: "POST",
      body: JSON.stringify({ user: "Diego", userName: "DiegoAlvarez" })
    });
    const result = await response.json();
    setUsers(result.data);
  };

  const handleUpdateUser = async () => {
    const response = await fetch("http://localhost:3000/api/users", {
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json"
      },
      method: "PUT",
      body: JSON.stringify({
        toUpdateUserName: "DiegoAlvarez",
        data: {
          name: "Juan Carlos"
        }
      })
    });
    const result = await response.json();
    setUsers(result.data);
  };

  return (
    <div>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <button onClick={handleAddUser}>Agregar usuario</button>
        <button onClick={handleUpdateUser}>Actualizar usuario</button>
        {users.map(user => (
          <h3>{user.name}</h3>
        ))}
      </main>
    </div>
  );
};

export default Users;
