import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

//Actions
import { addProductAction } from "../redux/actions/products.action";

//Images
import Main from "../assets/img/home.jpg";

//Components
import Header from "../components/Custom/Header/Header";
import MainTitle from "../components/Custom/Title/MainTitle/MainTitle";
import Product from "../components/Custom/Products/Product/Product";

//Containers
import MainContainer from "../components/Containers/MainContainer/MainContainer";
import ProductsContainer from "../components/Containers/ProductsContainer/ProductsContainer";

export default function Home() {
  //Redux hooks
  const dispatch = useDispatch();
  const { cart } = useSelector(store => store.products);

  const [data, setData] = useState([]);
  const [addFlag, setAddFlag] = useState(false);

  useEffect(() => {
    const handleProducts = async () => {
      const request = await fetch("http://localhost:3000/api/products");
      const result = await request.json();
      console.log(result);
      setData(result.data);
    };

    handleProducts();
  }, []);

  //Funciones
  const handleAddProduct = data => {
    let newCart;
    let isNewProduct = cart.indexOf(
      cart.find(product => product.id === data.id)
    );
    if (isNewProduct !== -1) {
      newCart = cart.map(product =>
        product.id === data.id ? { ...product, qty: product.qty + 1 } : product
      ); //[{id:1, qty:2}, {id: 2, qty: 1}]
    } else {
      newCart = [...cart, data];
    }

    dispatch(addProductAction({ newCart, price: data.price }));
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <MainContainer>
          <div className="flex flex-col justify-start w-full md:w-1/2">
            <MainTitle
              color="blue"
              title="Para gente "
              span="cool"
              align="left"
            />
            <p className="text-left mt-10 text-lg	text-black font-light	">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat.
            </p>
            <button
              className={`${styles.btn} bg-blue text-white mt-5 w-1/2 md:w-1/3`}
            >
              Carrito de compras
            </button>
          </div>
          <Image src={Main} alt="Home" width="600" height="600" />
        </MainContainer>
        <ProductsContainer>
          {data?.map(product => (
            <Product
              data={product}
              key={product.id}
              handleAddProduct={handleAddProduct}
            />
          ))}
        </ProductsContainer>
      </main>
    </div>
  );
}
