import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../../../styles/Home.module.css";

export default function Home() {
  const [formValues, setFormValues] = useState({
    stock: 10,
    info: {
      description: "Prueba descripción 1",
      sku: "products-1"
    }
  });

  const handleCreateProduct = async e => {
    e.preventDefault();
    const request = await fetch("http://localhost:3000/api/products", {
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json"
      },
      method: "POST",
      body: JSON.stringify(formValues)
    });
    const result = await request.json();
    console.log(result);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={e => handleCreateProduct(e)}>
          <input
            type="text"
            placeholder="Nombre del producto"
            onChange={e =>
              setFormValues({ ...formValues, name: e.target.value })
            }
          />
          <input
            type="number"
            placeholder="Precio del producto"
            onChange={e =>
              setFormValues({ ...formValues, price: e.target.value })
            }
          />
          <input type="submit" value="Guardar" />
        </form>
      </main>
    </div>
  );
}
