import React from "react";
import { useRouter } from "next/router";

import Head from "next/head";

const UserName = () => {
  const { query } = useRouter();
  console.log(query);
  return (
    <div>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>UserName</main>
    </div>
  );
};

export default UserName;
